/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{html,js}",
    "./dist/index.html"    
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#003909",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#002204",
        "inverse-on-surface": "#313030",
        "on-tertiary-fixed": "#001945",
        "background": "#131313",
        "surface-container-low": "#1c1b1b",
        "on-surface-variant": "#c0c9bb",
        "surface-tint": "#88d982",
        "tertiary-fixed-dim": "#b0c6ff",
        "surface-bright": "#393939",
        "outline": "#8a9386",
        "primary": "#88d982",
        "on-tertiary-fixed-variant": "#00429c",
        "secondary": "#e9c349",
        "error-container": "#93000a",
        "on-tertiary-container": "#adc4ff",
        "inverse-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "primary-fixed-dim": "#88d982",
        "on-tertiary": "#002d6f",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-highest": "#353534",
        "tertiary-fixed": "#d9e2ff",
        "on-secondary": "#3c2f00",
        "on-secondary-fixed-variant": "#574500",
        "tertiary-container": "#184da7",
        "surface-dim": "#131313",
        "on-error": "#690005",
        "surface-variant": "#353534",
        "primary-fixed": "#a3f69c",
        "outline-variant": "#41493e",
        "surface-container-high": "#2a2a2a",
        "secondary-container": "#af8d11",
        "error": "#ffb4ab",
        "secondary-fixed": "#ffe088",
        "secondary-fixed-dim": "#e9c349",
        "surface-container": "#201f1f",
        "on-primary-fixed-variant": "#005312",
        "on-secondary-fixed": "#241a00",
        "on-secondary-container": "#342800",
        "primary-container": "#065f18",
        "tertiary": "#b0c6ff",
        "inverse-primary": "#1b6d24",
        "surface": "#131313",
        "on-primary-container": "#86d881",
        "on-surface": "#e5e2e1"
      },
      fontFamily: {
        "headline": ["Lexend"],
        "body": ["Plus Jakarta Sans"],
        "label": ["Plus Jakarta Sans"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },  
};
